include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - example/**
    - '**.g.dart'

linter:
  rules:
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
