name: flutter_carplay_plus
description: "Flutter library to allow integration with Apple Carplay devices."
version: 0.0.1

#TODO (Redc4ke): Swap to stable once released
environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.27.7
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9
  pigeon: ^18.0.0
  melos: ^5.2.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlusPlugin