// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum CarplayConnectionStatus: Int {
  case connected = 0
  case background = 1
  case disconnected = 2
  case unknown = 3
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CoreHostApi {
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CoreHostApiSetup {
  /// The codec used by CoreHostApi.
  /// Sets up an instance of `CoreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CoreHostApi?) {
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CoreFlutterApiProtocol {
  func onConnectionStatusChanged(status statusArg: CarplayConnectionStatus, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class CoreFlutterApi: CoreFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }
  func onConnectionStatusChanged(status statusArg: CarplayConnectionStatus, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_carplay_plus.CoreFlutterApi.onConnectionStatusChanged"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger)
    channel.sendMessage([statusArg.rawValue] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
